name: "Github CD"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: SSH to server and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nghiatran0502/crawler-website
          tags: type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Deploy
        uses: applyboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            pwd
