name: "Github CD"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  cd:
    name: SSH to server and deploy
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nghiatran0502/crawler-website
          tags: type=raw,value={{date 'YYYY-MM-DD'}}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker rm -f website | true
            docker images --format '{{.Repository}}:{{.Tag}}' | grep 'nghiatran0502/crawler-website' | xargs -r docker rmi
            docker run --net crawler --name website -p 3100:80 nghiatran0502/crawler-website:2024-07-24
